enum actionTypes  {
        LOGIN_START = "LOGIN_START",
        LOGIN_SUCCESS = "LOGIN_SUCCESS",
        LOGIN_FAILURE = "LOGIN_FAILURE",
        CLIENT_SEARCH_START = "CLIENT_SEARCH_START",
        CLIENT_SEARCH_SUCCESS = "CLIENT_SEARCH_SUCCESS",
        CLIENT_SEARCH_FAILURE = "CLIENT_SEARCH_FAILURE",
        CLIENT_LOAD_POINTER_RESET = "CLIENT_SEARCH_POINTER_RESET",
        INFINITE_CLIENT_LOADER_START = "INFINITE_CLIENT_LOADER_START",
        INFINITE_CLIENT_LOADER_STOP = "INFINITE_CLIENT_LOADER_STOP",
        INFINITE_CLIENT_LOADER_WAS_STOPED = "INFINITE_CLIENT_LOADER_WAS_STOPED",
        SET_CLIENT_LOAD_PATH_AND_QUERY = "SET_CLIENT_SEARCH_PATH_AND_QUERY",
}

export default actionTypes; 
