enum actionTypes  {
        LOGIN_START = "LOGIN_START",
        LOGIN_SUCCESS = "LOGIN_SUCCESS",
        LOGIN_FAILURE = "LOGIN_FAILURE",
        CLIENT_SEARCH_START = "CLIENT_SEARCH_START",
        CLIENT_SEARCH_SUCCESS = "CLIENT_SEARCH_SUCCESS",
        CLIENT_SEARCH_FAILURE = "CLIENT_SEARCH_FAILURE",
        CLIENT_SEARCH_POINTER_RESET = "CLIENT_SEARCH_POINTER_RESET",
}

export default actionTypes;
