
export const LOGIN_START =  "LOGIN_START"; 
export const LOGIN_SUCCESS =  "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CLIENT_SEARCH_START =  "CLIENT_SEARCH_START"; 
export const CLIENT_SEARCH_SUCCESS =  "CLIENT_SEARCH_SUCCESS";
export const CLIENT_SEARCH_FAILURE = "CLIENT_SEARCH_FAILURE";
export const CLIENT_SEARCH_POINTER_RESET = "CLIENT_SEARCH_POINTER_RESET";
